// <auto-generated />
using System;
using ESW_Shelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ESW_Shelter.Data.Migrations
{
    [DbContext(typeof(ShelterContext))]
    [Migration("20181213003200_RemoveUsersInfoTable")]
    partial class RemoveUsersInfoTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ESW_Shelter.Models.Roles", b =>
            {
                b.Property<int>("RoleID")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("RoleName")
                    .IsRequired();

                b.HasKey("RoleID");

                b.ToTable("Roles");
            });

            modelBuilder.Entity("ESW_Shelter.Models.Users", b =>
            {
                b.Property<int>("UserID")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("City")
                    .HasMaxLength(40);

                b.Property<bool>("ConfirmedEmail");

                b.Property<DateTime>("DateOfBirth");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256);

                b.Property<string>("Password")
                    .IsRequired()
                    .HasMaxLength(12);

                b.Property<string>("Phone");

                b.Property<string>("PostalCode")
                    .HasMaxLength(10);

                b.Property<int>("RoleID");

                b.Property<string>("Street")
                    .HasMaxLength(100);

                b.HasKey("UserID");

                b.ToTable("Users");
            });
#pragma warning restore 612, 618
        }
    }
}
